'use strict';
let width = 8;
let height = 10;
let area = width * height;
console.log('area: ', area);
console.log('typeof area: ', typeof area);
let bill = 1001;
let payment = 211334;
let change = payment - bill;
console.log('change: ', change);
console.log('typeof change: ', typeof change);
let quizzes = 60;
let midterm = 70;
let final = 90;
let grade = (quizzes + midterm + final) / 3;
console.log('grade: ', grade);
console.log('typeof grade: ', typeof grade);
let firstName = 'Tev';
let lastName = 'Nicolas';
let fullName = firstName + ' ' + lastName;
console.log('fullName: ', fullName);
console.log('typeof fullName: ', typeof fullName);
let pH = 8;
let isAcidic = pH < 7;
console.log('isAcidic: ', isAcidic);
console.log('typeof isAcidic: ', typeof isAcidic);
let headCount = 250;
let isSparta = headCount === 300;
console.log('isSparta: ', isSparta);
console.log('typeof isSparta: ', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('motto: ', motto);
console.log('typeof motto: ', typeof motto);
